<!DOCTYPE html>
<html lang="zxx">

<!-- Mirrored from theme-vessel-templates.theme-vessel.ey.r.appspot.com/logdy/main/register-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Jul 2020 02:16:08 GMT -->
<head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '../../../www.googletagmanager.com/gtm5445.html?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-W24T6W7');</script>
    <!-- End Google Tag Manager -->
    <title>Logdy - Login and Register HTML5 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <!-- External CSS libraries -->
    <link type="text/css" rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="assets/fonts/font-awesome/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="assets/fonts/flaticon/font/flaticon.css">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon" >

    <!-- Google fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800%7CPoppins:400,500,700,800,900%7CRoboto:100,300,400,400i,500,700">

    <!-- Custom Stylesheet -->
    <link type="text/css" rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" type="text/css" id="style_sheet" href="assets/css/skins/default.css">

</head>
<body id="top">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W24T6W7"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="page_loader"></div>

<!-- Login 2 start -->
<div class="login-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="form-section">
                    <div class="logo-2">
                        <a href="">
                            <img src="/assets/img/logos/logo-2.png" alt="logo">
                        </a>
                    </div>
                    <h3>ĐĂNG KÍ TÀI KHOẢN</h3>
                    <?php echo $this->flashSession->output() ?>
                    <?php echo $this->tag->form("signup/register"); ?>
                    
                        <div class="form-group form-box">
                            <?php echo $form->render('name'); ?>
                            <i class="flaticon-user"></i>
                        </div>
                        <div class="form-group form-box">
                            <?php echo $form->render('email'); ?>
                            <i class="flaticon-mail-2"></i>
                        </div>
                        <div class="form-group form-box">
                            <?php echo $form->render('password'); ?>
                            <i class="flaticon-password"></i>
                        </div>
                        <div class="form-group form-box">
                            <?php echo $form->render('password_confirm'); ?>
                            <i class="flaticon-password"></i>
                        </div>

                        <div class="form-group mb-0 clearfix">
                            <?php echo $form->render('submit'); ?>
                            
                        </div>
                        <div class="extra-login clearfix">
                            <span>Or Login With</span>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                 <!--   <p>Already a member? <a href="login-2.html" class="thembo"> Login here</a></p> -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Login 2 end -->

<!-- External JS libraries -->
<script src="assets/js/jquery-2.2.0.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<!-- Custom JS Script -->

</body>

<!-- Mirrored from theme-vessel-templates.theme-vessel.ey.r.appspot.com/logdy/main/register-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Jul 2020 02:16:08 GMT -->
</html>


<style>
    .errorMessage{
        color:red;
        font-weight:bold;
        text-align:center;
    }
    
    
</style>

















