
	<div class="container">
		<div class="jumbotron">
			<h1 class="display-4">Phalcon App</h1>
			<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
			<hr class="my-4">
			<p>Nó sử dụng các lớp tiện ích cho kiểu chữ và khoảng cách đến không gian nội dung bên trong thùng chứa lớn hơn.</p>
			<a class="btn btn-primary btn-lg" href="signup" role="button">
				<i class="fa fa-github"></i>
				Đăng kí tại đây
			</a>
		</div>
	</div>


<?php



if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>STT</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

