<div class="container">
    <h3><i class="fa fa-pencil"></i> Sửa bài viết</h3>
    <!-- Show Flash Session Data -->
    <p><?= $this->flashSession->output() ?></p>

    <?php
        # URL Segments
        $uri_segments = explode("/", $this->request->getUri());
    ?>
    <?= $this->tag->form("article/edit/submit"); ?>

        <div class="form-group">
            <label for="title">Tiêu đề bài viết</label>
            <?= $form->render('title'); ?>
        </div>

        <div class="form-group">
            <label for="description">Nội dung bài viết</label>
            <?= $form->render('description'); ?>
        </div>

        <div class="form-group">
            <?= $form->render('save'); ?>
            <?= $form->render('publish'); ?>
        </div>
        
        <?= $form->render('eid', ['value' => $uri_segments[3]]); ?>

        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
    <?= $this->tag->endForm() ?>
</div>