<!DOCTYPE html>
<html lang="zxx">

<!-- Mirrored from theme-vessel-templates.theme-vessel.ey.r.appspot.com/logdy/main/login-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Jul 2020 02:13:46 GMT -->
<head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '../../../www.googletagmanager.com/gtm5445.html?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-W24T6W7');</script>

    <!-- End Google Tag Manager -->
    <title>Logdy - Login and Register HTML5 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    
    <!-- External CSS libraries -->
    <link type="text/css" rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/fonts/font-awesome/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/fonts/flaticon/font/flaticon.css">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/x-icon" >

    <!-- Google fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800%7CPoppins:400,500,700,800,900%7CRoboto:100,300,400,400i,500,700">

    <!-- Custom Stylesheet -->
    <link type="text/css" rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" type="text/css" id="style_sheet" href="/assets/css/skins/default.css">

</head>
<body id="top">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W24T6W7"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
                  
<!-- End Google Tag Manager (noscript) -->
<div class="page_loader"></div>

<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Phalcon</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <?= $this->tag->linkTo(["", '<i class="fa fa-home" aria-hidden="true"></i> Home <span class="sr-only">(current)</span>', "class" => "nav-link"]); ?>
                    </li>
                    
                    <li class="nav-item active">
                        <?php
                            # Check User Login
                            if ($this->session->has('IS_LOGIN'))
                            {
                                echo $this->tag->linkTo(
                                    [
                                    "article/create", 
                                    '<i class="fa fa-plus" aria-hidden="true"></i> Add Article <span class="sr-only">(current)</span>', 
                                    "class" => "nav-link"
                                    ]
                                );
                            }
                        ?>
                    </li>

                    
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <?php
                        # Check User Login
                        if ($this->session->has('IS_LOGIN'))
                        {
                            echo $this->tag->linkTo
                            (
                                [
                                "user/profile",
                                '<i class="fa fa-user" aria-hidden="true"></i> Profile',
                                "class" => "btn btn-light"
                                ]
                            );

                            echo "&nbsp;";

                            echo $this->tag->linkTo
                            (
                                [
                                "user/logout",
                                '<i class="fa fa-sign-out" aria-hidden="true"></i> Logout',
                                "class" => "btn btn-light"
                                ]
                            );


                        } else 
                        {
                            echo $this->tag->linkTo
                            (
                                [
                                "user/login",
                                '<i class="fa fa-sign-in" aria-hidden="true"></i> Login',
                                "class" => "btn btn-light"
                                ]
                            );
                            echo "&nbsp;";
    
                            echo $this->tag->linkTo
                            (
                                [
                                "signup/register",
                                '<i class="fa fa-sign-in" aria-hidden="true"></i> Register',
                                "class" => "btn btn-light"
                                ]
                            );
                        }
                    ?>
                </form>
            </div>
    </nav>

<!-- Login 2 start -->
<div class="login-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            <?php echo $this->getContent(); ?>
            </div>
        </div>
    </div>
</div>
<!-- Login 2 end -->

<!-- External JS libraries -->
<script src="/assets/js/jquery-2.2.0.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<!-- Custom JS Script -->
</body>

<!-- Mirrored from theme-vessel-templates.theme-vessel.ey.r.appspot.com/logdy/main/login-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Jul 2020 02:13:52 GMT -->
</html>
